### ISSUE TITLE
Testing in Laravel 5.5-dev

### ISSUE THREAD

**Issue by drjoju** [nWidart/laravel-menus#10]
Hi,

I suppose is a silly question, but how can I test the package in Laravel 5.5-dev. 

I try
 "nwidart/laravel-menus": "dev-master"
or 
 "nwidart/laravel-menus": "@dev"

But always says me:

`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nwidart/laravel-menus dev-master -> satisfiable by nwidart/laravel-menus[dev-master].
    - Conclusion: remove laravel/framework 5.5.x-dev
    - nwidart/laravel-menus dev-master requires illuminate/view 5.4.* -> satisfiable by illuminate/view[5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.9].
    - don't install illuminate/view 5.4.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/view v5.4.0|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/view v5.4.13|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/view v5.4.17|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/view v5.4.19|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/view v5.4.27|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/view v5.4.9|don't install laravel/framework 5.5.x-dev
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].

`
Thanks and best regards

**Comment by nWidart** [comment]
Hi,

There isn't a 5.5 compatabible version just yet. Will happen soon.

In the future please use the issue tracker for questions and issue. :)


Kind regards,

---

Nicolas Widart
@NicolasWidart <https://twitter.com/nicolaswidart>

**Comment by drjoju** [comment]
Hi nWidart,

One more question and one suggestion.

Sorry for my ignorance but where is the issue tracker? I only see Issues in a tab and Issues at the top.

The suggestion is, why don't you make the master-dev open so we can download for testing in newer versions of the Laravel framework?

Thanks and best regards

**Comment by nWidart** [comment]
Here: https://github.com/nWidart/laravel-modules/issues <https://github.com/nWidart/laravel-modules/issues>

---

Nicolas Widart
@NicolasWidart <https://twitter.com/nicolaswidart>

**Comment by nWidart** [comment]
5.5 support has been tagged as `1.0.0`.

Laravel 5.4 is on the `0.x` tags only.
