### ISSUE TITLE
Menu not showing the translated title

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [nWidart/laravel-menus#11]
Hi @nWidart, I am working on creating menus, everything worked well, but when I run the following code in view: 
`{!! Menu::instance('Main Menu')->getName() !!}`
which output the menu name.

Is it possible to have the title of menu instead? 
Because in that case we can get the title for different locale.

See that in screenshot below:
![main menu title issue](https://user-images.githubusercontent.com/12660951/29909632-41e2d044-8e40-11e7-9eb4-61593f7ba7e3.png)

Thank you!

**Comment by nWidart** [comment]
Hi,

I don't think you can get the title like that.
Maybe you can of the `Menu` class.

**Comment by kashifullahwebdeveloper** [comment]
Thank you for quick reply, @nWidart.  

Could you please give me some hints?

**Comment by nWidart** [comment]
Example here: https://github.com/Idavoll/Menu/blob/2.0/Providers/MenuServiceProvider.php#L109

**Comment by kashifullahwebdeveloper** [comment]
One more stupid question? Could you please make me understand? why we have same module at two different places one at vendor folder in root and other in Modules folder?
such as vendor/nwidart/laravel-menus in vendor folder by you and other in Modules with named Menu?

**Comment by nWidart** [comment]
That has nothing to do with this package.
The menu module is different than this package. It handles the UI etc. for instance.

**Comment by kashifullahwebdeveloper** [comment]
If I am not wrong, the link: https://github.com/Idavoll/Menu/blob/2.0/Providers/MenuServiceProvider.php#L109,  you provided to me pointing to items of menu whereas I need to get the translated version of menu itself?

**Comment by nWidart** [comment]
Yes.. but it's the same principle. Just look through that module if you need more.

**Comment by kashifullahwebdeveloper** [comment]
Okay, thank you for the hints :), let me try that and see if i can figure it out.
