### ISSUE TITLE
v1 working correctly?

### ISSUE THREAD

**Issue by drjoju** [nWidart/laravel-menus#12]
Hi,

I'm trying to implement the v1 in Laravel 5.5 and BootStrap 4.0.

Following the instructions I publish the views to /resources/views/vendor/nwidart/menus with

php artisan vendor:publish --provider="Nwidart\Menus\MenusServiceProvider"

Them I make some changes in the views and use it as follows

  ```
      Menu::create($menuName, function ($menu) {           
           $menu->setView('menus::default');
            $menu->url('/', 'Home', []);
            $menu->route('contactus', 'Contacto', [], []);
        });
```
I modified the file /resources/views/vendor/nwidart/menus/default.blade.php with

```
<ul class="navbar-nav ml-auto">
  @include('menus::menu')
</ul>
```

But nothing changes. So I decide to do it with presenters and created a /App/Presenters/FrontMenuNavbarPresenter

and modifid the /config/menus.php file with

```
return [

    'styles' => [
        //'navbar' => \Nwidart\Menus\Presenters\Bootstrap\NavbarPresenter::class,
        'navbar' => \App\Presenters\FrontMenuNavbarPresenter::class,
       ....
    ],

    'ordering' => false,

];

```
Obviously I created the FrontMenuNavbarPresenter.php with somithing like
```

    /**
     * {@inheritdoc }.
     */
    public function getOpenTagWrapper()
    {
        return PHP_EOL . '<ul class="navbar-nav ml-auto">' . PHP_EOL;
    }
```

And nothing appears in the HTML.

Finally I decide to add the presenter in code  like 
```

    Menu::create($menuName, function ($menu) {           
           $menu->setPresenter(\App\Presenters\FrontMenuNavbarPresenter::class);
            $menu->url('/', 'Home', []);
            $menu->route('contactus', 'Contacto', [], []);
        });
```

And It works well.

What I doing wrong in the views and in config solution or is an issue?

Thanks and best regards

**Comment by nWidart** [comment]
It should be working yes as tests are green (granted, not everything is covered, yet).

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by asaelmedina** [comment]
could you solve it?
