### ISSUE TITLE
Use Spatie/html instead of laravelcollective/html

### ISSUE THREAD

**Issue by vpratfr** [nWidart/laravel-menus#21]
This would help make the code of presenters much cleaner. For instance, an existing method:

        return '<li' . $this->getActiveState($item) . '>
			<a href="' . $item->getUrl() . '" ' . $item->getAttributes() . ' class="nav-link">'
            . $item->title . '</a></li>' . PHP_EOL;

Note that above code is using some *rendering* functionnality placed in the MenuItem class (which should not be there, see #19)

Using Spatie/html, we can rewrite this as

        $link = html()->a($item->getUrl())
            ->addClass('nav-link')
            ->attributes($item->attributes)
            ->html($item->title);

        return html()->element('li')
            ->addClass('nav-item')
            ->addClassIf($item->isActive(), 'active')
            ->addChild($link);

**Comment by nWidart** [comment]
Hello,

I'm not really a fan of using a this.
Since it's in presenters, you should already be able to use it in your own presenters.

**Comment by vpratfr** [comment]
This could also simplify the way HTML is rendered. Presenters would return Elements instead of returning strings. Which allows manipulating the elements (add class, add children, change attributes, etc.).

**Comment by vpratfr** [comment]
Nevermind. Ended up rewriting your package for a few things I needed. 

Fixed in https://github.com/marvinlabs/laravel-menus/
