### ISSUE TITLE
Support Laravel 5.8?

### ISSUE THREAD

**Issue by gpibarra** [nWidart/laravel-menus#36]

**Comment by nWidart** [comment]
Yup, feel free to contribute.

**Comment by juniorvilasboas** [comment]
I am not able to install in Laravel 5.8.8

**Comment by nWidart** [comment]
Support has been added by @anyb1s , you can start testing it with `4.0-dev`.

**Comment by baradhili** [comment]
hmm 
`composer require nwidart/laravel-menus:4.0-dev`

`  [InvalidArgumentException]                                                  
  Could not find package nwidart/laravel-menus in a version matching 4.0-dev`
