### ISSUE TITLE
My Code Doesn't Work !

### ISSUE THREAD

**Issue by efectn** [nWidart/laravel-menus#51]
`Menu::create('navbar', function($menu) {
            // URL, Title, Attributes
            foreach (Menus::tree() as $item) {
                $menu->url('/'.$item->name, $item->name, ['target' => 'blank','class' => 'deneem']);
                foreach ($item['children'] as $child) {
                    echo "<ol>D" . $child->name . "</ol>";
                    $menu->dropdown('Settings', function ($sub) {
                        $sub->url('settings/account', $child->name);
                        $sub->url('settings/password', 'Password');
                        $sub->url('settings/design', 'Design');
                    });
                }
            }
        });`

in dropdown menu i cant access $child varible why ?

**Comment by efectn** [comment]
Solve ?

**Comment by pishguy** [comment]
@efectn did you see pull request in this link? did you test it?

https://github.com/nWidart/laravel-menus/pull/32
